<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-IVQQQE2" ignored="2" name="Test" tests="3" failures="1" timestamp="2021-03-24T21:05:15 IST" time="12.398" errors="0">
  <testcase name="getResponseCode" time="4.039" classname="testcases.GetResponseCodeTest"/>
  <testcase name="getResponseId" time="2.865" classname="testcases.GetResponseIdTest">
    <failure type="java.lang.AssertionError" message="expected [600f9a8d8f798e2a4d5f979e] but found [60428aafc041c16716f73cd7]">
      <![CDATA[java.lang.AssertionError: expected [600f9a8d8f798e2a4d5f979e] but found [60428aafc041c16716f73cd7]
at testcases.GetResponseIdTest.getResponseId(GetResponseIdTest.java:33)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getResponseId -->
  <testcase name="getResponseShipsCount" time="4.009" classname="testcases.GetResponseShipsCountTest"/>
  <testcase name="@BeforeSuite extentReportSetUp" time="0.0" classname="generics.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite extentReportSetUp -->
  <testcase name="@BeforeSuite extentReportSetUp" time="0.0" classname="generics.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite extentReportSetUp -->
</testsuite> <!-- Test -->
